# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=56)),
                ('Summary', models.TextField()),
                ('Employer', models.CharField(max_length=128)),
                ('From', models.DateField()),
                ('To', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=56)),
                ('Title', models.CharField(max_length=56)),
                ('Summary', models.TextField()),
                ('Location', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=128)),
                ('Phone', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SortOrder', models.IntegerField()),
                ('Description', models.TextField()),
                ('Resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
        ),
        migrations.AddField(
            model_name='employmentinfo',
            name='Resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='EmploymentInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.EmploymentInfo'),
        ),
    ]
