# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinfo',
            name='To',
            field=models.DateField(blank=True, null=True),
        ),
    ]
